### ISSUE TITLE
Object management

### ISSUE THREAD

**Issue by jakubfabian** [jakubfabian/topo#1]
need brainstorming with bottle of wine to discuss object (wall spot etc.) management

**Comment by Loisel** [comment]
`RouteGeometry` decouples routes and walls. For starters.

**Comment by jakubfabian** [comment]
shouldnt routes stay attached to several walls? -- otherwise we end up with these filter chains in views....

**Comment by Loisel** [comment]
They do. Magic of [ManyToMany Through](https://docs.djangoproject.com/es/1.9/topics/db/models/#extra-fields-on-many-to-many-relationships)

**Comment by jakubfabian** [comment]
Holy shit, fancy fancy.
