### ISSUE TITLE
Fix the way we add routes

### ISSUE THREAD

**Issue by jakubfabian** [jakubfabian/topo#12]
When adding a route, we need to begin with a geom string... I couldnt use a null value .. but we want an empty to begin with...
fix that!

**Comment by Loisel** [comment]
I suggest the following:
1. Klick add route in wall dev view.
2. New template: Choose existing route (from spot's route list) or 
   - can't find your route? Create new route
   - new view: enter route metadata
   - return to list of existing routes
3. Draw route polygon (either show the leaflet dynamically as soon as an existing route is selected or show a new view with the leaflet and a back button, I personally prefer the first option)

**Comment by Loisel** [comment]
This issue is discussed implicitly in [issue 22](https://github.com/jakubfabian/topo/issues/22).
