### ISSUE TITLE
Extend spot model 

### ISSUE THREAD

**Issue by jakubfabian** [jakubfabian/topo#16]
Spot Model should be extended by
Anfahrt
parking including optional geoms

star rating(overall rating)
optional average approach hike time

... need further brainstorming

**Comment by Loisel** [comment]
The average rating can be generated dynamically I'd say.

**Comment by Loisel** [comment]
All map decorations that are related to spots go into their own classes which reference spot as a foreign key (many-to-one). I think we can close this for now.
