### ISSUE TITLE
Discussion about Site Navigation

### ISSUE THREAD

**Issue by jakubfabian** [jakubfabian/topo#23]
At our next meeting, we should really discuss site navigation...
I have no idea how to organize that efficiently.
I had a look at django-sitetree and while that works nicely for what it does -- it does not fit our current model.

If we want to use it, that would imply to put a lot of extra stuff into the template context.

**Comment by datenhahn** [comment]
Attached you find a suggestion I drew with evolus pencil (free multi os opensource software for wireframes) . PNG export did not work so I screenshottet the result to view it without the program (used shutter for screenshot, very nice linux program).
http://pencil.evolus.vn/

I suggest everyone draws some suggestions brainstorming-like with not too much detail to collect many different basic ideas so we have some starter for the discussion.

My suggestion is to have a always present multi stage "searchable dropdown" (=combobox) filter. When you start selecting one filter-type (country, area, etc.) the other choices narrow down accordingly. You always have the choice to start with walls (or routes?) right from the start. Additionally I would offer an easy suggestion-textfield quicksearch. Just hammer in whatever you like and it tries to figure out what you mean. E.g. you type Kochel, and it lists all walls from kochel in a "dropdown like" suggestion list (but not a dropdown ;) ). You type "kochel foo" and only "foo wall" matches. If only one result matches and you press enter you are directly taken to it, if there are multiple ones, you can select from the list or continue typing until only one matches. 

I suggest using bootstrap.js as basic layouting js lib and something like selectize.js for the comboboxes.
http://selectize.github.io/selectize.js/

Attached you find the zipped (github wants zip) pencil file

![auswahl_025](https://cloud.githubusercontent.com/assets/13999666/14048883/88e27796-f2b1-11e5-88bb-9fd403fdc4a1.png)
[startpage.ep.zip](https://github.com/jakubfabian/topo/files/189751/startpage.ep.zip)

**Comment by datenhahn** [comment]
Good book not too long book about Usability Design:
Steve Krug, "Don't make me think"

http://www.uxbooth.com/articles/10-usability-lessons-from-steve-krugs-dont-make-me-think/

**Comment by Loisel** [comment]
Sexy. +1 on navi discussion. Tuesday?

**Comment by datenhahn** [comment]
for me tuesday would be fine

**Comment by jakubfabian** [comment]
+1 Dienstag

**Comment by jakubfabian** [comment]
want:
- single field for search all
- custom fields for advanced filtered search initially hidden behind button

**Comment by datenhahn** [comment]
packed discussion into pencil draft, feel free to adjust, and as always, this is only meant as draft, logo, font, etc. are only examples

[startpage2.ep.zip](https://github.com/jakubfabian/topo/files/194460/startpage2.ep.zip)
![auswahl_029](https://cloud.githubusercontent.com/assets/13999666/14126669/fe608c56-f612-11e5-9d2c-4f9380618313.png)
![auswahl_028](https://cloud.githubusercontent.com/assets/13999666/14126670/fea567e0-f612-11e5-9c50-ed416764966a.png)
![auswahl_027](https://cloud.githubusercontent.com/assets/13999666/14126671/fea79100-f612-11e5-91a1-bab690b9d76a.png)

**Comment by datenhahn** [comment]
Map taken from: http://hikebikemap.org/

A hiking OSM layer. We should play around with different layers (hiking seems to make sense)

But others may fit neater in our design expectations, I like that one, as it has more friendly colors than the other ones (I think it is mapnik): http://map.datenhahn.de/
