### ISSUE TITLE
Discussion about where to put input validation, custom forms, module substructuring

### ISSUE THREAD

**Issue by datenhahn** [jakubfabian/topo#24]
When developing on the add/edit spot feature I came across some questions:
- where and how do we input validation most elegant? (e.g. Spotname meets a certain regex)
- what is the best way to escape user input?
- How do I build custom forms which use my custom fields?
- if logic gets more complex, where do we put it? everything in views works for now, but maybe not forever. Maybe I am wrong and this indicates a wrong use of django and the logic I mean should reside in different places anyway

sample structure to illustrate my point:
views.py
applogic/spot.py
applogic/area.py

and maybe later
applogic/spot/foo.py
applogic/spot/bar.py

I did not find anything on that topic in the internet, so maybe my idea of what to do how in django is wrong

**Comment by jakubfabian** [comment]
put the view stuff in views....
if it gets too much, just make it a new app.
e.g. user model
custom forms validation in forms.py
you can overwrite the validate function.

what do you mean by custom fields for custom forms?

escape user input means? It either fits the model or not -- that is what validate does?

**Comment by datenhahn** [comment]
with escape I mean prevent the user to use html or javascript e.g. in a spot name which is executed then in all other users browsers. It should be clear how and where we escape values (django offers autoescape or html escape filters in the template) to prevent XSS-attacks.

https://docs.djangoproject.com/en/1.9/ref/templates/builtins/

ok, so I think I just have to get more into custom forms regarding the validation stuff. We maybe should define some rules about valid characters in spot, wall, etc. names e.g. [-_a-zA-z0-9]+

**Comment by datenhahn** [comment]
Regarding using subapplications to structure the project and wiring them together to a app (like fabi mentioned) here is a stackoverflow post which explains it:

http://stackoverflow.com/questions/2670031/large-django-application-layout

**Comment by datenhahn** [comment]
Architecture Decision:
- use django subapplications to break down the code (when necessary)
- use django forms validation
