### ISSUE TITLE
Page Layout

### ISSUE THREAD

**Issue by jakubfabian** [jakubfabian/topo#28]
Small Banner,
Big Map

Create index view and template.

Change CSS styles as needed

**Comment by datenhahn** [comment]
packed discussion into pencil draft, feel free to adjust, and as always, this is only meant as draft, logo, font, etc. are only examples

The quick-edit "filter-drop-down" should be styled differently than the other dropdowns to clearly distinguish it from the rest.

Breadcrumbs over searchbox when something was selected.

GPS locator in the right bottom corner (maybe other position?) for easy access when on-site.

We should orientate the style on googlemaps (further compare needed) or some other mapping sites.

logo should be always visible and click on logo has to take the user back to the startpage.

[startpage2.ep.zip](https://github.com/jakubfabian/topo/files/194460/startpage2.ep.zip)
![auswahl_029](https://cloud.githubusercontent.com/assets/13999666/14126669/fe608c56-f612-11e5-9d2c-4f9380618313.png)
![auswahl_028](https://cloud.githubusercontent.com/assets/13999666/14126670/fea567e0-f612-11e5-9c50-ed416764966a.png)
![auswahl_027](https://cloud.githubusercontent.com/assets/13999666/14126671/fea79100-f612-11e5-91a1-bab690b9d76a.png)

**Comment by chhuber** [comment]
would add a single-colored banner, or a nice image header, which contains logo, search bar and so on.
Buttons seem a little lost on the map

**Comment by datenhahn** [comment]
Finally had time to update the graphics, new suggestion, again, just rough draft, open for discussion.
[startpage3.ep.zip](https://github.com/jakubfabian/topo/files/203305/startpage3.ep.zip)
![auswahl_033](https://cloud.githubusercontent.com/assets/13999666/14262666/f29fdc16-fab6-11e5-9a6d-6441e96cd466.png)
![auswahl_032](https://cloud.githubusercontent.com/assets/13999666/14262702/0e7b2fda-fab7-11e5-9b3d-e253f001addc.png)
![auswahl_031](https://cloud.githubusercontent.com/assets/13999666/14262701/0e7a777a-fab7-11e5-9fa2-c437cead9706.png)
![auswahl_030](https://cloud.githubusercontent.com/assets/13999666/14262703/0ea9d81c-fab7-11e5-8341-79ff69a7cbcd.png)

**Comment by datenhahn** [comment]
843e84d7cf9b34528997fba03d2cdd229858cbdf

**Comment by datenhahn** [comment]
Current status:

![auswahl_040](https://cloud.githubusercontent.com/assets/13999666/14368047/a48c321a-fd1b-11e5-92bb-9698993d7e58.jpg)

**Comment by datenhahn** [comment]
Still a lot missing:
- correct formatting of the lists
- different sizes of the "infobox" depending on mode
- toggle of the info box
- breadcrumbs
- minor design fixes (don't really like the dark-green borders)
- refactoring and reordering of css
- refactoring of templates

and surely lots of other stuff

**Comment by datenhahn** [comment]
Pulled out the "Guided Filter" (the filter under the searchbox) into this ticket: #34 ,

Closing this ticket now as we have a "good enough" state
