### ISSUE TITLE
Design and set up user model.

### ISSUE THREAD

**Issue by Loisel** [jakubfabian/topo#31]
We need a user model. This should also be implemented mid-term since a lot of the logic will require something like `if user is in group` or similar in the views. It would be nice also to start thinking about the interplay of users and the miroutes model (walls, routes, spots).

This definitely needs a dev meeting.

**Comment by jakubfabian** [comment]
Did you notice the user model in the topo/users app?
Just saying that there is already a User model and I am not sure if you mean you want a more sophisticated model or if you didnt notice.

**Comment by Loisel** [comment]
A more sophisticated model. 
- Do we, e.g., need something like a spot manager?
- Does it make sense to add users that own a wall to a wall manager group?
- What are the user fields?
  I guess more issues pop up during the implementation.

**Comment by datenhahn** [comment]
@jakubfabian activated the existing model and annotated some views with certain roles, should be enough for the start?

**Comment by Loisel** [comment]
The roles do it. I think the next step is community features. Closed for now.
