### ISSUE TITLE
datatables for our tables

### ISSUE THREAD

**Issue by Loisel** [jakubfabian/topo#40]
Hey there, I suggest we use one (https://datatables.net) of the numerous jQuery datatable plugins to show on our routepool and link-route pages.

Pros:
- No bike re-invention.
- Search, scroll, filter and everything you wet-dream of.

Semipro:
- We can switch to another plugin quite easily if one is not usable anymore due to whatever reason (all deal with basic html tables)

Con:
- Third-party dependency.

datatables has bootstrap and bower support so its a no-brainer to install. What u think?

**Comment by jakubfabian** [comment]
Top, but we would deliver the js code ourselves right?
What do you mean with having a third party dependency?

On 11.10.2016 12:02, Loisel wrote:

> Hey there, I suggest we use one (https://datatables.net) of the numerous jQuery datatable plugins to show on our routepool and link-route pages.
> 
> Pros:
> - No bike re-invention.
> - Search, scroll, filter and everything you wet-dream of.
> 
> Semipro:
> - We can switch to another plugin quite easily if one is not usable anymore due to whatever reason (all deal with basic html tables)
> 
> Con:
> - Third-party dependency.
> 
> datatables has bootstrap and bower support so its a no-brainer to install. What u think?

## 

```
      _\|/_
      (o o)
```

  +----oOO-{_}-OOo-+
  |  Jakub Fabian  |
  +---------------*/

**Comment by Loisel** [comment]
yep we deliver. I mean that at some day some strange thing can happen to their library and we do not understand it :P

**Comment by datenhahn** [comment]
the beauty of opensource software, if strange things happen, we will understand and fix it :)

**Comment by Loisel** [comment]
This is settled. Nice.
