### ISSUE TITLE
Google api reference

### ISSUE THREAD

**Issue by jakubfabian** [jakubfabian/topo#41]
I just saw that google api reference
<link href='https://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>

snug into the rendered templates....

where does that come from.

I would prefer not to have stuff loaded from outside sources all the time.

**Comment by datenhahn** [comment]
check, added a webfont for playing around with the design and never fixed it. Now it is a regular bower dependency. Reopen the ticket if you find more
