### ISSUE TITLE
zoom on route if clicked in list

### ISSUE THREAD

**Issue by jakubfabian** [jakubfabian/topo#48]
I think it would be cool if the map would zoom (set leaflet bounds) so that the route would be displayed in its entirety when we click on it in the left pane route list

**Comment by jakubfabian** [comment]
to clarify:
Not by hover but by click on row and maybe even introduce a lense symbol on top of that to make it clear you can click on a row.

**Comment by Loisel** [comment]
click on list item on the left zoom to bounds of polyline.
