### ISSUE TITLE
Spot create/edit view

### ISSUE THREAD

**Issue by datenhahn** [jakubfabian/topo#6]
To facilitate drilling down to walls in an area, there are different area-categories, each one more specific than the last.

country -> area -> spot -> wall

Currently spots can not be created in the UI, but only manually in the database. Users should be able to add a new spot or edit an existing spot.
The spot should be marked by the user on the map.
- generate a new template for spot (create/edit)
- new view where spot template is loaded (no id new, id edit existing)
- add url-mapping for spots-view to urls.py
- use Django forms
- see existing code for editing routes as example

**Comment by datenhahn** [comment]
first try: 877ae124769a0968c556a51a25531bb2071039d9

showing and editing a single spot works, but it is not tied into the application (only accessible by url). Also for creating new spots, all spots of the area should be visible.

**Comment by datenhahn** [comment]
merged current draft into master so it can be continued by others

**Comment by datenhahn** [comment]
just pushed small next step, passing the spot list with the other spots of the area to the view. But can't display it with the default field edit widget.

Someone knows how to add a javascript initializer to the default form map created by LeafletWidget?

@chhuber ?

**Comment by jakubfabian** [comment]
I also played around a bit with the django-leaflet stuff but that kind of a dissapointing area.
At least more complicated than using leaflet java script directly.
But if you get a hang of it -- nice.
Otherwise maybe jus stick to javascript....

**Comment by datenhahn** [comment]
adding spots now works, also added some custom marker images (these are not the final ones ;) ) . Input validation is still missing, as well as edit and spot click-actions/mouseovers

**Comment by datenhahn** [comment]
adding spots has to be more intuitive, also we should decide on some nice spot images (or revert to the standard markers)

**Comment by jakubfabian** [comment]
Looks promising as it is now. Would suggest that the functionality considering the maps is already ok as is.
Need to add some more model fields for additional data like parking approch etc.
But this can be added once we reached a "functional prototype" stage where we try to add a real topo/location.
